	; this line for VSCode proper formating
TILEDATA_NO_COLLISION	= 0
TILEDATA_COLLISION		= %11111111
TILEDATA_RESTORE_TILE	= 1
TILEDATA_COLLIDABLE		= 8*16
TILEDATA_BREAKABLE		= 13*16

TILEDATA_FUNC_MASK		= %11110000
TILEDATA_ARG_MASK		= %00001111

TILE_IDX_INVALID = $ff

TILEDATA_FUNC_ID_MONSTERS	= 1
TILEDATA_FUNC_ID_ITEMS		= 6
TILEDATA_FUNC_ID_RESOURCES	= 7
TILEDATA_FUNC_ID_CONTAINERS	= 11
TILEDATA_FUNC_ID_DOORS		= 12
TILEDATA_FUNC_ID_BREAKABLES	= 13
TILEDATA_FUNC_ID_COLLISION	= 15

TILEDATA_STORYTELLING = 0
TIMEDATA_MESSAGE_HOME_DOOR		= 0
TIMEDATA_MESSAGE_FRIEND_DOOR	= 1

ROOMS_MAX = 64