	; this line for VSCode proper formating
; monster types
MONSTER_TYPE_ENEMY	= 0
MONSTER_TYPE_ALLY	= 1

; statuses
MONSTER_STATUS_INIT		= 0
MONSTER_STATUS_IMPACTED	= $80
MONSTER_STATUS_FREEZE	= $40

; status time
MONSTER_STATUS_FREEZE_TIME = BUFF_FREEZE_TIME