	; this line for VSCode proper formating
BREAKABLE_SPAWN_RATE_MAX	= 255
BREAKABLE_SPAWN_RATE_DELTA	= 256/8 ; destroying 8 breakable items makes their spawning chance = 255 - BREAKABLE_SPAWN_RATE_MAX
MONSTER_SPAWN_RATE_MAX		= 250
MONSTER_SPAWN_RATE_DELTA	= 256/16

RES_POTION_HEALTH_VAL		= 5
RES_POPSICLE_PIE_MANA_VAL	= 25
RES_CABBAGE_HEALTH_VAL		= 1

RES_EMPTY				= 0
RES_HEALTH_MAX 			= 10
RES_SNOWFLAKES_MAX		= 80
RES_POTION_HEALTH_MAX	= 10
RES_POPSICLE_PIE_MAX	= 10
RES_CLOTHS_MAX			= 5
RES_SWORD_MAX			= 1
RES_SPOON_MAX			= 1

BUFF_FREEZE_TIME		= 80

GAME_REQ_ROOM_INIT	= 0 | GAME_REQ
GAME_REQ_LEVEL_INIT	= 1 | GAME_REQ
GAME_REQ_PAUSE		= 2 | GAME_REQ
GAME_REQ_ROOM_DRAW	= 3 | GAME_REQ
GAME_REQ_END_HOME	= 4 | GAME_REQ
