	; this line for VSCode proper formating
BREAKABLE_SPAWN_RATE_MAX	= 255
BREAKABLE_SPAWN_RATE_DELTA	= 256/8 ; destroying 8 breakable items makes their spawning chance = 255 - BREAKABLE_SPAWN_RATE_MAX
MONSTER_SPAWN_RATE_MAX		= 250
MONSTER_SPAWN_RATE_DELTA	= 256/16

ITEM_STATUS_NOT_ACQUIRED	= 0
ITEM_STATUS_ACQUIRED	= 1
ITEM_STATUS_USED		= 2